### PR TITLE
Switching implementation from mod.rs to file names based on module name

### PR DESCRIPTION
**Pull request by Hasnabruzzn**
as per https://github.com/BenLeadbetter/midi2/issues/17
Affected modules
- channel_voice1
- channel_voice2
- ci (also adding path to README.md in ci.rs)
- detail
- flex_date
- sysex7 (also adding path to README.md in sysex7.rs)
- sysex8
- system_common (also adding path to README.md in system_common.rs)
- ump_stream
- utility

### CODE REVIEW

**Comment by Hasnabruzzn** [comment]
Please note: This is my very first contribution to any project and I had first to learn how to do this with GitHub (hope everything is ok)

**Comment by BenLeadbetter** [comment]
Thanks for the PR! 

New changes should go against `develop` rather than main. (I should probably make `develop` the default branch and update the contribution docs.)

I've changed the target branch but this has unfortunately created a couple of conflicts. Let me know if you have any queries regarding their resolution.

**Comment by Hasnabruzzn** [comment]
Sorry for creating a mess!

**Comment by BenLeadbetter** [comment]
Not at all! Like I said - the defaults are confusing. I'm still sussing out this open contribution thing myself- you're the first 😅💙

**Comment by BenLeadbetter** [comment]
Would you like a hand rebasing this branch? I'm planning another release soon and it would be good to include this patch, if possible.

**Comment by Hasnabruzzn** [comment]
Should I do the fork based on the develop branch? For that I have to delete my current fork (GitHub tries to scare me:
image
)
... or is it ok to stay based on main and do the pull request into the develop branch?

**Comment by BenLeadbetter** [comment]
Hmm. I would have though that you could "rebase" your branch on my upstream develop branch and these errors would go away. Shouldn't need to delete your fork !

**Pull request closed without merging**
